### ISSUE TITLE
Linux: invalid memory access during libacm block decoding

### ISSUE THREAD

**Issue by bryanperris** [kevinbentley/Descent3#95] opened 2024-04-19 22:14 UTC
Reproduce Steps:
* Compile latest source on Fedora 39
* Export the fake SDL21 CD PATH environment variable (did not provide any manual track files)
* Execute ./Descent3
* Immediately see the giant sun background then process crash

GDB Details:
Thread 1 "Descent3" received signal SIGSEGV, Segmentation fault.
(anonymous namespace)::InternalAudioDecoder::UnpackLinear (decoder=..., id=9, col=0, atEOF=@0x7fffffff9caf: false)
    at /home/bperris/base/dev/Descent3/libacm/libacm.cpp:585
585	    pBlock[pos] = decoder.m_pMidBuffer[offset - middleIndex];

Workaround: Disable block decoding for libacm, no doubt it probably breaks audio

**Comment by JeodC** [comment] 2024-04-19 23:30
This sounds like a duplicate of #83 but on Linux instead of Mac.

**Comment by winterheart** [comment] 2024-04-20 06:25
Yes, it is.

**Closed by winterheart** 2024-04-20 06:25 UTC
Labels: duplicate
